version: 2

sources:
  - name: lighthouse-mayra
    schema: erp_banvic
    tables:
      - name: agencias
      - name: clientes
      - name: colaborador_agencia
      - name: colaboradores
      - name: contas
      - name: propostas_credito
      - name: transacoes